/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourismRouteImport } from './routes/tourism'
import { Route as RanksRouteImport } from './routes/ranks'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContributorRouteImport } from './routes/contributor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdministrativeUnitsRouteImport } from './routes/administrative-units'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlacesIdRouteImport } from './routes/places.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'

const TourismRoute = TourismRouteImport.update({
  id: '/tourism',
  path: '/tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const RanksRoute = RanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorRoute = ContributorRouteImport.update({
  id: '/contributor',
  path: '/contributor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativeUnitsRoute = AdministrativeUnitsRouteImport.update({
  id: '/administrative-units',
  path: '/administrative-units',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIdRoute = PlacesIdRouteImport.update({
  id: '/places/$id',
  path: '/places/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/administrative-units': typeof AdministrativeUnitsRoute
  '/auth': typeof AuthRoute
  '/contributor': typeof ContributorRoute
  '/events': typeof EventsRouteWithChildren
  '/ranks': typeof RanksRoute
  '/tourism': typeof TourismRoute
  '/events/$id': typeof EventsIdRoute
  '/places/$id': typeof PlacesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/administrative-units': typeof AdministrativeUnitsRoute
  '/auth': typeof AuthRoute
  '/contributor': typeof ContributorRoute
  '/events': typeof EventsRouteWithChildren
  '/ranks': typeof RanksRoute
  '/tourism': typeof TourismRoute
  '/events/$id': typeof EventsIdRoute
  '/places/$id': typeof PlacesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/administrative-units': typeof AdministrativeUnitsRoute
  '/auth': typeof AuthRoute
  '/contributor': typeof ContributorRoute
  '/events': typeof EventsRouteWithChildren
  '/ranks': typeof RanksRoute
  '/tourism': typeof TourismRoute
  '/events/$id': typeof EventsIdRoute
  '/places/$id': typeof PlacesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/administrative-units'
    | '/auth'
    | '/contributor'
    | '/events'
    | '/ranks'
    | '/tourism'
    | '/events/$id'
    | '/places/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/administrative-units'
    | '/auth'
    | '/contributor'
    | '/events'
    | '/ranks'
    | '/tourism'
    | '/events/$id'
    | '/places/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/administrative-units'
    | '/auth'
    | '/contributor'
    | '/events'
    | '/ranks'
    | '/tourism'
    | '/events/$id'
    | '/places/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdministrativeUnitsRoute: typeof AdministrativeUnitsRoute
  AuthRoute: typeof AuthRoute
  ContributorRoute: typeof ContributorRoute
  EventsRoute: typeof EventsRouteWithChildren
  RanksRoute: typeof RanksRoute
  TourismRoute: typeof TourismRoute
  PlacesIdRoute: typeof PlacesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tourism': {
      id: '/tourism'
      path: '/tourism'
      fullPath: '/tourism'
      preLoaderRoute: typeof TourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranks': {
      id: '/ranks'
      path: '/ranks'
      fullPath: '/ranks'
      preLoaderRoute: typeof RanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor': {
      id: '/contributor'
      path: '/contributor'
      fullPath: '/contributor'
      preLoaderRoute: typeof ContributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrative-units': {
      id: '/administrative-units'
      path: '/administrative-units'
      fullPath: '/administrative-units'
      preLoaderRoute: typeof AdministrativeUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$id': {
      id: '/places/$id'
      path: '/places/$id'
      fullPath: '/places/$id'
      preLoaderRoute: typeof PlacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
  }
}

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdministrativeUnitsRoute: AdministrativeUnitsRoute,
  AuthRoute: AuthRoute,
  ContributorRoute: ContributorRoute,
  EventsRoute: EventsRouteWithChildren,
  RanksRoute: RanksRoute,
  TourismRoute: TourismRoute,
  PlacesIdRoute: PlacesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

